name: pyviz
channels:
  - informaticslab
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - antlr-python-runtime=4.7.2
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - backcall=0.1.0
  - bleach=3.1.0
  - bokeh=1.1.0
  - boost-cpp=1.68.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cairo=1.14.12
  - cartopy=0.17.0
  - certifi=2019.3.9
  - cf-units=2.1.1
  - cffi=1.12.2
  - cftime=1.0.3.4
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=0.8.1
  - cryptography=2.6.1
  - curl=7.64.1
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=1.1.5
  - dask-core=1.1.5
  - datashape=0.5.4
  - decorator=4.4.0
  - defusedxml=0.5.0
  - descartes=1.1.0
  - distributed=1.26.1
  - entrypoints=0.3
  - expat=2.2.5
  - fiona=1.8.6
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - futures-compat=1.0
  - gdal=2.4.1
  - geopandas=0.4.1
  - geos=3.7.1
  - geotiff=1.4.3
  - gettext=0.19.8.1
  - giflib=5.1.7
  - glib=2.56.2
  - graphite2=1.3.13
  - graphviz=2.38.0
  - harfbuzz=1.9.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.0
  - icu=58.2
  - idna=2.8
  - imageio=2.5.0
  - intake=0.4.4
  - ipydatawidgets=4.0.0
  - ipykernel=5.1.0
  - ipyscales=0.3.0
  - ipython=7.4.0
  - ipython_genutils=0.2.0
  - ipyvolume=0.5.1
  - ipywebrtc=0.4.3
  - ipywidgets=7.4.2
  - iris=2.2.0
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9c
  - json-c=0.13.1
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kealib=1.4.10
  - kiwisolver=1.0.1
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1
  - libdap4=3.19.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgdal=2.4.1
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libpng=1.6.36
  - libpq=11.2
  - libsodium=1.0.16
  - libspatialindex=1.9.0
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libtool=2.4.6
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - llvmlite=0.28.0
  - locket=0.2.0
  - lxml=4.3.3
  - mapclassify=2.0.1
  - markdown=2.6.11
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mistune=0.8.4
  - msgpack-numpy=0.4.4.2
  - msgpack-python=0.6.1
  - multipledispatch=0.6.0
  - munch=2.3.2
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - nbserverproxy
  - ncurses=6.1
  - netcdf4=1.5.0.1
  - networkx=2.2
  - notebook=5.7.8
  - numba=0.43.1
  - numpy=1.15.4
  - olefile=0.46
  - openblas=0.3.5
  - openjpeg=2.3.1
  - openssl=1.1.1b
  - owslib=0.17.1
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.7.2
  - pandocfilters=1.4.2
  - pango=1.40.14
  - parso>0.4.0
  - partd=0.3.9
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.0.3
  - pixman=0.34.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.2
  - proj4=5.2.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - psutil=5.6.1
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pyepsg=0.4.0
  - pygments=2.3.1
  - pykdtree=1.3.1
  - pyke=1.1.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyproj=1.9.6
  - pyqt=5.6.0
  - pyrsistent=0.14.11
  - pyshp=2.1.0
  - pysocks=1.6.8
  - python=3.6.7
  - python-dateutil=2.8.0
  - python-graphviz=0.10.1
  - python-snappy=0.5.4
  - pythreejs=2.0.2
  - pytz=2018.9
  - pywavelets=1.0.2
  - pyyaml=5.1
  - pyzmq=18.0.1
  - qtconsole=4.4.3
  - readline=7.0
  - requests=2.21.0
  - rtree=0.8.3
  - ruamel=1.0
  - ruamel.yaml=0.15.92
  - scikit-image=0.15.0
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=41.0.0
  - shapely=1.6.4
  - sip=4.18.1
  - six=1.12.0
  - snappy=1.1.7
  - sortedcontainers=2.1.0
  - sqlite=3.26.0
  - tblib=1.3.2
  - terminado=0.8.2
  - testpath=0.3.1
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=6.0.2
  - traitlets=4.3.2
  - traittypes=0.2.1
  - tzcode=2018g
  - udunits2=2.2.27.6
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - xarray=0.12.1
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.12
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.4
  - zlib=1.2.11
  - dbus=1.13.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=8.2.0
  - pcre=8.43
  - qt=5.6.3
  - intake_hypothetic=0.1.2
  - iris_hypothetic=0.1.4
  - jade_utils=0.1.7
  - mo_aws_earth=0.1.1
  - colorcet=2.0.1
  - datashader=0.7.0
  - geoviews=1.6.2
  - geoviews-core=1.6.2
  - holoviews=1.12.0
  - hvplot=0.4.0
  - panel=0.4.0
  - param=1.9.0
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pyviz_comms=0.7.2
